import jsPDF from "jspdf";

export interface ReportCheck {
  diagnosis: string;
  severity: string;
  confidence: number;
  symptoms: string[];
  recommendations?: string[] | null;
  language?: string;
  created_at: string;
}

export interface ReportUser {
  name?: string;
  email?: string;
}

const BRAND = "#0284c7";
const TEXT = "#111827";
const MUTED = "#6b7280";

function line(doc: jsPDF, y: number) {
  doc.setDrawColor(220);
  doc.line(15, y, 195, y);
}

function header(doc: jsPDF, title: string) {
  doc.setFillColor(BRAND);
  doc.rect(0, 0, 210, 22, "F");
  doc.setTextColor("#ffffff");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text("AI HealthBot", 15, 14);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(title, 195, 14, { align: "right" });
  doc.setTextColor(TEXT);
}

function footer(doc: jsPDF) {
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(MUTED);
    doc.text(
      "Generated by AI HealthBot • For educational purposes only — not a medical diagnosis.",
      105,
      290,
      { align: "center" }
    );
    doc.text(`Page ${i} of ${pageCount}`, 195, 290, { align: "right" });
  }
}

function severityColor(sev: string): [number, number, number] {
  if (sev === "high") return [220, 38, 38];
  if (sev === "moderate") return [217, 119, 6];
  return [22, 163, 74];
}

function writeCheck(doc: jsPDF, check: ReportCheck, startY: number): number {
  let y = startY;
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(TEXT);
  doc.text(check.diagnosis || "Health Assessment", 15, y);

  const [r, g, b] = severityColor(check.severity);
  doc.setFillColor(r, g, b);
  doc.roundedRect(160, y - 5, 35, 7, 2, 2, "F");
  doc.setTextColor("#ffffff");
  doc.setFontSize(9);
  doc.text(check.severity.toUpperCase(), 177.5, y, { align: "center" });
  doc.setTextColor(TEXT);

  y += 6;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(MUTED);
  doc.text(
    `${new Date(check.created_at).toLocaleString()}  •  Confidence: ${check.confidence}%  •  Language: ${(check.language || "en").toUpperCase()}`,
    15,
    y
  );
  y += 8;

  doc.setTextColor(TEXT);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("Symptoms Reported", 15, y);
  y += 5;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  const symText = (check.symptoms || []).join(", ") || "—";
  const symLines = doc.splitTextToSize(symText, 180);
  doc.text(symLines, 15, y);
  y += symLines.length * 5 + 3;

  if (check.recommendations && check.recommendations.length) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.text("Recommendations", 15, y);
    y += 5;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    check.recommendations.forEach((rec) => {
      const recLines = doc.splitTextToSize(`• ${rec}`, 180);
      if (y + recLines.length * 5 > 275) {
        doc.addPage();
        header(doc, "Health Report");
        y = 32;
      }
      doc.text(recLines, 15, y);
      y += recLines.length * 5;
    });
    y += 3;
  }

  line(doc, y);
  return y + 6;
}

export function generateHealthReport(check: ReportCheck, user: ReportUser = {}) {
  const doc = new jsPDF();
  header(doc, "Personal Health Report");

  let y = 32;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("Prepared for", 15, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(user.name || user.email || "Guest User", 50, y);
  y += 5;
  if (user.email) {
    doc.setTextColor(MUTED);
    doc.text(user.email, 50, y);
    doc.setTextColor(TEXT);
    y += 5;
  }
  doc.setTextColor(MUTED);
  doc.text(`Report generated: ${new Date().toLocaleString()}`, 50, y);
  doc.setTextColor(TEXT);
  y += 8;
  line(doc, y);
  y += 6;

  y = writeCheck(doc, check, y);

  y += 4;
  doc.setFillColor(254, 242, 242);
  doc.roundedRect(15, y, 180, 24, 3, 3, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(185, 28, 28);
  doc.text("⚠ Emergency Guidance", 20, y + 7);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(TEXT);
  const emg = doc.splitTextToSize(
    "If you experience severe chest pain, difficulty breathing, sudden weakness, loss of consciousness, or uncontrolled bleeding — call 108 (India) immediately or go to the nearest emergency room.",
    170
  );
  doc.text(emg, 20, y + 13);
  y += 30;

  doc.setFontSize(8);
  doc.setTextColor(MUTED);
  const disclaimer = doc.splitTextToSize(
    "Medical Disclaimer: This report is generated by an AI assistant and is intended for informational and educational purposes only. It is not a substitute for professional medical advice, diagnosis, or treatment. Always consult a qualified healthcare provider for any medical concerns.",
    180
  );
  doc.text(disclaimer, 15, y);

  footer(doc);
  doc.save(`healthbot-report-${new Date(check.created_at).toISOString().slice(0, 10)}.pdf`);
}

export function generateFullHistoryReport(checks: ReportCheck[], user: ReportUser = {}) {
  const doc = new jsPDF();
  header(doc, "Complete Health History");

  let y = 32;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("Prepared for", 15, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(user.name || user.email || "Guest User", 50, y);
  y += 5;
  doc.setTextColor(MUTED);
  doc.text(`Total records: ${checks.length}  •  Generated: ${new Date().toLocaleString()}`, 50, y);
  doc.setTextColor(TEXT);
  y += 8;
  line(doc, y);
  y += 6;

  checks.forEach((c) => {
    if (y > 240) {
      doc.addPage();
      header(doc, "Complete Health History");
      y = 32;
    }
    y = writeCheck(doc, c, y);
  });

  footer(doc);
  doc.save(`healthbot-history-${new Date().toISOString().slice(0, 10)}.pdf`);
}
